name: puppeteer print action
run-name: ${{ github.actor }} is printing on  GitHub Actions 🚀
on: [push]
jobs:
  Puppeteer-Print-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Convert https://github.com to PDF
        uses: "imbhargav5/puppeteer-pdf-action@master"
        with:
          url: https://github.com
          output-file-path: github.pdf
