name: puppeteer print action
run-name: ${{ github.actor }} is printing on  GitHub Actions 🚀
on: [push]
jobs:
  html2pdf-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: html2pdf-step
        uses: ntdesmond/html2pdf-action@v1
        with:
          path: ./file.html
          output: ./file.pdf
          options: |
            {"format": "A4"}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./file.pdf
      - uses: actions/download-artifact@v4
        with:
          name: file.pdf
      - name: Display structure of downloaded files
        run: ls -R
