name: puppeteer print action
run-name: ${{ github.actor }} is printing on  GitHub Actions 🚀
on: [push]
jobs:
  html2pdf-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: html2pdf-step
        uses: ntdesmond/html2pdf-action@v1
        with:
          path: ./file.html
          output: ./file.pdf
          options: |
            {"format": "A4"}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./file.pdf
      - name: Save production artifacts
        uses: actions/download-artifact@v4
      - name: Display structure of downloaded files
        run: ls -R
