name: puppeteer print action
run-name: ${{ github.actor }} is printing on  GitHub Actions 🚀
on: [push]
jobs:
  html2pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ntdesmond/html2pdf-action@v1
        with:
          path: ./file.html
          output: ./file.pdf
          options: |
            {"format": "A4"}
      - uses: actions/upload-artifact@v3
        with:
          path: ./file.pdf

